services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  producer:
    build:
      context: C:/projects/demo
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  consumer:
    build:
      context: C:/projects/rabbitmqconsumerdemo
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

volumes:
  rabbitmq_data:
